name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  init:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install QT
      uses: jurplel/install-qt-action@v2.14.0
      
  build_standard:
    runs-on: windows-latest
    needs: init
    steps:
    - name: Configure Standard
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPROJECT_NAME="VideoLow" -DHARDWARE_ACCELERATION_DEFAULT=0 -DWITH_CONSOLE=0

    - name: Build Standard
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build_nvidia:
    runs-on: windows-latest
    needs: init
    steps:
    - name: Configure Nvidia
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPROJECT_NAME="VideoLow_Nvidia" -DHARDWARE_ACCELERATION_DEFAULT=1 -DWITH_CONSOLE=0

    - name: Build Nvidia
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build_amd:
    runs-on: windows-latest
    needs: init
    steps:
    - name: Configure AMD
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPROJECT_NAME="VideoLow_AMD" -DHARDWARE_ACCELERATION_DEFAULT=2 -DWITH_CONSOLE=0

    - name: Build AMD
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build_debug:
    runs-on: windows-latest
    needs: init
    steps:
    - name: Configure DBEUG
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPROJECT_NAME="VideoLow_DEBUG" -DHARDWARE_ACCELERATION_DEFAULT=0 -DWITH_CONSOLE=1

    - name: Build DEBUG
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
